---
backupDestinationPath: "E:\\Documents\\developpement\\webdrone\\gitbackup"
organisations:
- name: "manaty"
  token: null
  username: "myusername"
  password: "mypassword"
  gitRepoUrls: null
- name: "meveo"
  token: null
  username: "smichea"
  password: "M@nil2lovie"
  gitRepoUrls:
  - "https://github.com/meveo-org/mv-calendar.git"
  - "https://github.com/meveo-org/mv-template.git"
